name: MCTrapsShop
version: 1.0.0
author: KajmaczeK
main: eu.mctraps.shop.MCTrapsShop
website: https://mctraps.eu
commands:
  smsshop:
    description: "Główna komenda pluginu"
    usage: /<command>
    permission: smsshop.admin
  voucher:
    description: "Komenda do obsługi voucherów"
    usage: /<command> <list|info|add|generate|remove|edit>
    permission: smsshop.voucher
permissions:
  tools.smsshop.*:
    description: "Wszystkie uprawnienia pluginu"
    children:
      smsshop.admin
      smsshop.voucher
  tools.smsshop.admin:
    description: "Pozwala na użycie głównej komendy"
    default: op
  tools.smsshop.voucher:
    description: "Pozwala na obsługę voucherów"
    default: op